export const SUPERVISING_LECTURER = 'SUPERVISING_LECTURER';
export const HEAD_OF_PROGRAM = 'HEAD_OF_PROGRAM';
export const HEAD_OF_DEPARTMENT = 'HEAD_OF_DEPARTMENT';
export const HOMEROOM_LECTURER = 'HOMEROOM_LECTURER';
