const CHAT = 'CHAT';
const NOTI = 'NOTI';
const DOCUMENT = 'DOCUMENT';
const REPORT = 'REPORT';
const DASHBOARD = 'DASHBOARD';
const DETAIL = 'DETAIL';

export { CHAT, NOTI, REPORT, DOCUMENT, DASHBOARD, DETAIL };
